# Generated by Django 4.2.15 on 2024-08-26 20:18

import api.managers
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=1024, unique=True)),
                ('refresh_token', models.CharField(max_length=1024, unique=True)),
                ('refresh_token_expires', models.DateTimeField(blank=True, null=True)),
                ('ip', models.CharField(max_length=255, verbose_name='IP-адрес')),
                ('user_agent', models.CharField(max_length=255, verbose_name='User-Agent')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Сессия',
                'verbose_name_plural': 'Сессии',
                'ordering': ['-created'],
            },
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', api.managers.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='type',
        ),
        migrations.AddField(
            model_name='servicetype',
            name='ico',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='Иконка mdi-icons'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_online',
            field=models.BooleanField(default=False, verbose_name='Онлайн'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_ip',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Последний IP-адрес'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_online',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последняя активность'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('П', 'Пациент'), ('С', 'Сотрудник'), ('Г', 'Гость')], default='П', max_length=1, verbose_name='Роль'),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлен'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активность'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Администратор'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=256, verbose_name='Пароль'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email', 'phone'], name='api_user_email_19cb5c_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['first_name', 'last_name', 'patronymic'], name='api_user_first_n_7b46a6_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['date_joined', 'updated_at'], name='api_user_date_jo_6892ee_idx'),
        ),
        migrations.AddField(
            model_name='session',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['created'], name='api_session_created_cf4ebd_idx'),
        ),
    ]
