import type { Metadata } from 'next'
import { Jost } from 'next/font/google'
import '@/shared/styles/global.css'
import { ReactNode } from 'react'
import { Provider } from 'react-redux'
import { store } from '@/store'

const inter = Jost({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
	robots: 'index, follow',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: ReactNode
}>) {
	return (
		<html lang="ru">
			<body className={inter.className}>
				<Provider store={store}>{children}</Provider>
			</body>
		</html>
	)
}
