# Generated by Django 5.1 on 2024-10-05 07:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("employee", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("updated", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                ("address", models.CharField(blank=True, max_length=256, null=True, verbose_name="Адрес")),
                ("oms", models.CharField(max_length=16, verbose_name="ОМС")),
                ("snils", models.CharField(blank=True, max_length=16, null=True, verbose_name="СНИЛС")),
                ("inn", models.CharField(blank=True, max_length=12, null=True, verbose_name="ИНН")),
                ("passport", models.CharField(blank=True, max_length=128, null=True, verbose_name="Паспорт")),
                (
                    "patient_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="patients", to="core.patienttype"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="patient", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Пациент",
                "verbose_name_plural": "Пациенты",
                "unique_together": {("oms", "snils", "inn", "passport", "user")},
            },
        ),
        migrations.CreateModel(
            name="PatientBalance",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("updated", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0, message="Balance cannot be negative")],
                        verbose_name="Остаток средств",
                    ),
                ),
                (
                    "patient",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="balance", to="patient.patient"
                    ),
                ),
            ],
            options={
                "verbose_name": "Баланс пациента",
                "verbose_name_plural": "Балансы пациентов",
            },
        ),
        migrations.CreateModel(
            name="PatientCart",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("updated", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                ("diagnose", models.CharField(blank=True, max_length=256, null=True, verbose_name="Диагноз")),
                ("date_visit", models.DateField(verbose_name="Дата визита")),
                (
                    "status",
                    models.CharField(
                        choices=[("DRAFT", "Черновик"), ("ACTIVE", "Обслуживание"), ("ARCHIVE", "Архив")],
                        default="DRAFT",
                        max_length=32,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="carts", to="patient.patient"
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="patient_carts", to="employee.service"
                    ),
                ),
            ],
            options={
                "verbose_name": "Амбулаторная карта",
                "verbose_name_plural": "Амбулаторные карты",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="Agreement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("updated", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                ("start", models.TimeField(verbose_name="Начало")),
                ("end", models.TimeField(verbose_name="Конец")),
                (
                    "patient_cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="agreements", to="patient.patientcart"
                    ),
                ),
            ],
            options={
                "verbose_name": "Договор",
                "verbose_name_plural": "Договоры",
            },
        ),
        migrations.CreateModel(
            name="PatientPhone",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("updated", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                ("phone", models.CharField(max_length=20, verbose_name="Телефон")),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="phones", to="patient.patient"
                    ),
                ),
            ],
            options={
                "verbose_name": "Телефон",
                "verbose_name_plural": "Телефоны",
            },
        ),
        migrations.CreateModel(
            name="PatientSignature",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("updated", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                ("signature", models.CharField(max_length=128, verbose_name="Открытый ключ")),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="signatures", to="patient.patient"
                    ),
                ),
            ],
            options={
                "verbose_name": "ЭЦП",
                "verbose_name_plural": "ЭЦП",
            },
        ),
        migrations.CreateModel(
            name="Talon",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("updated", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                ("result", models.TextField(verbose_name="Результат")),
                (
                    "agreement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="talons", to="patient.agreement"
                    ),
                ),
            ],
            options={
                "verbose_name": "Талон",
                "verbose_name_plural": "Талоны",
            },
        ),
        migrations.AddIndex(
            model_name="patientcart",
            index=models.Index(fields=["-created"], name="patient_pat_created_40942b_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="patientsignature",
            unique_together={("signature", "patient")},
        ),
    ]
