# Generated by Django 5.1 on 2024-10-05 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("updated", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                (
                    "payment_id",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="ID платежа YooKassa"),
                ),
                ("payment_url", models.URLField(blank=True, null=True, verbose_name="Ссылка на оплату")),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("bank_card", "Банковская карта"),
                            ("sberbank", "SberPay"),
                            ("tinkoff_bank", "T‑Pay"),
                            ("sbp", "СБП (Система быстрых платежей)"),
                            ("yoo_money", "ЮMoney"),
                            ("balance", "С лицевого счета"),
                            ("cashless", "Безналичная оплата"),
                        ],
                        max_length=32,
                        null=True,
                        verbose_name="Способ оплаты",
                    ),
                ),
                (
                    "payer_type",
                    models.CharField(
                        choices=[("INDIVIDUAL", "Физическое лицо"), ("LEGAL", "ЮЛ / ИП")],
                        default="INDIVIDUAL",
                        max_length=32,
                        verbose_name="Тип плательщика",
                    ),
                ),
                (
                    "target",
                    models.CharField(
                        choices=[("BALANCE", "Пополнение баланса"), ("SERVICE", "Оплата услуги")],
                        max_length=32,
                        verbose_name="Цель оплаты",
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="Назначение платежа"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name="Сумма оплаты"
                    ),
                ),
                ("is_paid", models.BooleanField(default=False, verbose_name="Оплачен")),
                (
                    "expires_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Дата истечения срока действия"),
                ),
                ("captured_at", models.DateTimeField(blank=True, null=True, verbose_name="Дата оплаты счета")),
            ],
            options={
                "verbose_name": "Счет",
                "verbose_name_plural": "Счета",
                "ordering": ("-created",),
            },
        ),
        migrations.CreateModel(
            name="InvoiceOrder",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("updated", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                ("quantity", models.PositiveIntegerField(default=1, verbose_name="Количество")),
            ],
            options={
                "verbose_name": "Услуга по счету",
                "verbose_name_plural": "Услуги по счетам",
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("updated", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        null=True,
                        verbose_name="Сумма транзакции",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("DEPOSIT", "Доход"), ("WITHDRAWAL", "Расход"), ("TRANSFER", "Перевод средств")],
                        max_length=32,
                        verbose_name="Тип транзакции",
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="Описание транзакции"),
                ),
            ],
            options={
                "verbose_name": "Транзакция",
                "verbose_name_plural": "Транзакции",
                "ordering": ("-created",),
            },
        ),
    ]
