# Generated by Django 5.1 on 2024-10-05 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("business", "0001_initial"),
        ("employee", "0001_initial"),
        ("patient", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="invoices", to="patient.patient"
            ),
        ),
        migrations.AddField(
            model_name="invoiceorder",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="services", to="business.invoice"
            ),
        ),
        migrations.AddField(
            model_name="invoiceorder",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="orders", to="employee.service"
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="business.invoice",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="transactions", to="patient.patient"
            ),
        ),
    ]
